theme: "org.wso2.carbon.uuf.common.default.theme"

menus:
  - name: "main"
    items:
      - text: "Home"
        link: ""
        icon: "fw-home"
      - text: "Samples"
        link: ""
        submenus:
          - text: "UUF Cliet"
            link: ""
            submenus:
              - text: "Pushing a fragment"
                link: "/uuf-client/fragment"
              - text: "Pushing a template"
                link: "/uuf-client/template"
              - text: "Pushing a fragment with client side CSS and JS"
                link: "/uuf-client/fragment-with-resources"

errorPages:
  404: /foundation/error/404
  default: /foundation/error/default
