appName: Sample App
theme : org.wso2.carbon.uuf.common.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default
